language: python

python:
  - '3.4'
  - '3.5'
  - '3.6'

before_install:
  - python -V

install:
  - pip install "flake8==3.4" "pycodestyle==2.3.1" pep8-naming
  - python setup.py sdist bdist_wheel

before_script:
  - flake8 --version
  - flake8 -v .

script:
  - targz=$(ls dist/mg-toolkit*.tar.gz)
  - pip install -U $targz
  - mg-toolkit -d original_metadata -a ERP001178
  - if ! diff -q ERP001178.csv tests/ERP001178.csv &>/dev/null; then exit 1; fi
  - mg-toolkit -d bulk_download -a MGYS00002478
  - if ! diff -q MGYS00002478/4.1/non_coding_rna/ERR169332.5_8S_rRNA.RF00002.fa tests/ERR169332.5_8S_rRNA.RF00002.fa &>/dev/null; then exit 1; fi

notifications:
  slack:
    secure: D1lBmpLSuEeXIk/LYekDz+tzH9jxIGw+ocCI44Pwzxq8hLzQ9vSR6m4djogWLjmgw6eqxd+RVj9i/9+eccuHJ9CNTl+8Hy8p2i6ou/OjAR2gRry/wFOuSBJyX2Lc8/tA8kuYstkXgCE7RpoI40gH/ksI2yr/rUKLLd9yUPpo3kdZ3ZZ2qpiaz38n8Hojp3BDjjzWc1cQfGat59uF5Pkf3PPjv2fHQglBSph1ei2ldY77ui71BBDTetXFOPchRo2Xl0mDCu3BVtro8xpXhAWgfFCtuwqSqXYrOhGXAI20Rkp+ZUrEGTIDmUNyMLVBO+V7S8o2D/K4XtMQbrAnpo2y4fQRiuFHtl+5wS6oj6S8ICl/CfKDyENzEGDZjB6jQ0ygix/z4rmdYjPcc9T+zBE8FJnC3SBzTEEFvMPZOm/nGYOOIFhr8jdvS78jXemTndhvWiDYtRY9guL4vseF8Cg/msOsaKbr9ZmPomk0mqZZ6eNv+4lUJvpczo7DiAQIoMEg0yLT/51raEzQd0JdrrTg8ePvH+vfYEgzxTv+TuCJ8S/kbxkh4zRDfqTUT3gIH5Y7+onpMiOHkZYufbso00JHyJM+LzocjxC5pzJ7TJteMt7RrLll4qf2+DQQ0p+kSnxf/LZklGFY4xVnI52fDPQHqWWwj1GfN/eojHoviuMCnqo=
